export type ConnectionState =
  | 'UNPAIRED'
  | 'PAIRING'
  | 'CHALLENGING'
  | 'DISCOVERING'
  | 'CONNECTING'
  | 'CONNECTED'
  | 'DEGRADED'
  | 'DISCONNECTED'
  | 'UNAUTHORIZED'
  | 'SECRET_ROTATION_PENDING';
