export type ConnectionState =
  | 'UNPAIRED'
  | 'PAIRING'
  | 'CHALLENGE'
  | 'DISCOVERY'
  | 'CONNECTED_PENDING_HEARTBEAT'
  | 'CONNECTED'
  | 'DEGRADED'
  | 'DISCONNECTED'
  | 'UNAUTHORIZED'
  | 'SECRET_ROTATION_PENDING';
