<?php

use App\Http\Controllers\ApiDocumentationSpecController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Middleware\EnsureApiDocumentationAccess;
use App\Livewire\Account\ChangePassword;
use App\Livewire\Account\Profile;
use App\Livewire\Admin\Agencies\Backups as AgencyBackups;
use App\Livewire\Admin\Agencies\Form as AgencyForm;
use App\Livewire\Admin\Agencies\Import as AgencyImport;
use App\Livewire\Admin\Agencies\Index as AgenciesIndex;
use App\Livewire\Admin\Agencies\Map as AgenciesMap;
use App\Livewire\Admin\Agencies\Show as AgencyShow;
use App\Livewire\Admin\ApiDocumentation;
use App\Livewire\Admin\ApiTokens\Index as ApiTokensIndex;
use App\Livewire\Admin\ApiTools\DniTester;
use App\Livewire\Admin\ApiTools\RucTester;
use App\Livewire\Admin\DesignSystem;
use App\Livewire\Admin\Ruc\Imports as RucImports;
use App\Livewire\Admin\Ruc\Records as RucRecords;
use App\Livewire\Admin\Ruc\Show as RucShow;
use App\Livewire\Admin\Settings\AgencyBackups as AgencyBackupSettings;
use App\Livewire\Admin\Settings\ApiDocumentation as ApiDocumentationSettings;
use App\Livewire\Admin\Settings\Dni as DniSettings;
use App\Livewire\Admin\Settings\Ubigeos as UbigeoSettings;
use App\Livewire\Admin\Users\Form as UsersForm;
use App\Livewire\Admin\Users\Index as UsersIndex;
use App\Livewire\Admin\Users\Show as UsersShow;
use App\Livewire\Dashboard;
use App\Livewire\PublicAgencies\Index as PublicAgenciesIndex;
use App\Livewire\PublicAgencies\Show as PublicAgencyShow;
use App\Modules\Agencies\Http\Controllers\AgencyBackupDownloadController;
use App\Modules\Agencies\Http\Controllers\AgencyExportController;
use App\Modules\Agencies\Http\Controllers\AgencyImportPreviewController;
use App\Modules\Agencies\Http\Controllers\AgencyMoveController;
use App\Modules\Ruc\Http\Controllers\RucImportErrorsController;
use Illuminate\Support\Facades\Route;

Route::get('/', Dashboard::class)->middleware(['auth'])->name('dashboard');
Route::middleware('guest')->group(function (): void {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store'])->name('login.store');
});
Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->middleware('auth')->name('logout');
Route::view('/404', 'errors.404')->name('error.404');
Route::get('/admin/agencies', AgenciesIndex::class)->middleware(['auth'])->name('admin.agencies.index');
Route::get('/admin/agencies/export', AgencyExportController::class)->middleware(['auth'])->name('admin.agencies.export');
Route::get('/admin/agencies/backups', AgencyBackups::class)->middleware(['auth'])->name('admin.agencies.backups.index');
Route::get('/admin/agencies/backups/{backup}/download', AgencyBackupDownloadController::class)->middleware(['auth'])->name('admin.agencies.backups.download');
Route::get('/admin/agencies/map', AgenciesMap::class)->middleware(['auth'])->name('admin.agencies.map');
Route::get('/admin/agencies/import', AgencyImport::class)->middleware(['auth'])->name('admin.agencies.import');
Route::get('/admin/agencies/create', AgencyForm::class)->middleware(['auth'])->name('admin.agencies.create');
Route::get('/admin/agencies/{agency}/edit', AgencyForm::class)->middleware(['auth'])->name('admin.agencies.edit');
Route::get('/admin/agencies/{agency}', AgencyShow::class)->middleware(['auth'])->name('admin.agencies.show');
Route::get('/admin/users', UsersIndex::class)->middleware(['auth'])->name('admin.users.index');
Route::get('/admin/users/create', UsersForm::class)->middleware(['auth'])->name('admin.users.create');
Route::get('/admin/users/{user}/edit', UsersForm::class)->middleware(['auth'])->name('admin.users.edit');
Route::get('/admin/users/{user}', UsersShow::class)->middleware(['auth'])->name('admin.users.show');
Route::middleware(EnsureApiDocumentationAccess::class)->group(function (): void {
    Route::get('/docs', ApiDocumentation::class)->name('docs');
    Route::get('/docs/api', ApiDocumentation::class)->name('api.docs');
    Route::get('/docs/api/v1', ApiDocumentation::class)->name('api.docs.v1');
    Route::get('/docs/api/agencias', ApiDocumentation::class)->name('api.docs.agencies');
    Route::get('/docs/api/dni', ApiDocumentation::class)->name('api.docs.dni');
    Route::get('/docs/api/autenticacion', ApiDocumentation::class)->name('api.docs.authentication');
    Route::get('/docs/api/errores', ApiDocumentation::class)->name('api.docs.errors');
    Route::get('/docs/api/ruc', ApiDocumentation::class)->name('api.docs.ruc');
    Route::get('/docs/api/ruc/autenticacion', ApiDocumentation::class)->name('api.docs.ruc.authentication');
    Route::get('/docs/api/ruc/errores', ApiDocumentation::class)->name('api.docs.ruc.errors');
    Route::get('/docs/api/ruc/ejemplos', ApiDocumentation::class)->name('api.docs.ruc.examples');
    Route::get('/docs/openapi', ApiDocumentation::class)->name('api.docs.openapi');
    Route::get('/docs/api/openapi.yaml', ApiDocumentationSpecController::class)->name('api.docs.spec');
});
Route::get('/admin/api-tokens', ApiTokensIndex::class)->middleware(['auth'])->name('admin.api-tokens.index');
Route::get('/admin/api-tools/dni', DniTester::class)->middleware(['auth'])->name('admin.api-tools.dni');
Route::get('/admin/api-tools/ruc', RucTester::class)->middleware(['auth', 'throttle:ruc-admin-test'])->name('admin.api-tools.ruc');
Route::get('/admin/ruc', RucRecords::class)->middleware(['auth'])->name('admin.ruc.records');
Route::get('/admin/ruc/importaciones', RucImports::class)->middleware(['auth'])->name('admin.ruc.imports');
Route::get('/admin/ruc/importaciones/{import}/errores', RucImportErrorsController::class)->middleware(['auth'])->name('admin.ruc.imports.errors');
Route::get('/admin/ruc/{record}', RucShow::class)->middleware(['auth'])->name('admin.ruc.show');
Route::get('/admin/settings/dni', DniSettings::class)->middleware(['auth'])->name('admin.settings.dni');
Route::get('/admin/settings/api-documentation', ApiDocumentationSettings::class)->middleware(['auth'])->name('admin.settings.api-documentation');
Route::get('/admin/settings/agency-backups', AgencyBackupSettings::class)->middleware(['auth'])->name('admin.settings.agency-backups');
Route::get('/admin/settings/ubigeos', UbigeoSettings::class)->middleware(['auth'])->name('admin.settings.ubigeos');
Route::get('/admin/design-system', DesignSystem::class)
    ->middleware(['auth'])
    ->name('admin.design-system');
Route::get('/agencies', PublicAgenciesIndex::class)->name('public.agencies.index');
Route::get('/agencies/{code}', PublicAgencyShow::class)->name('public.agencies.show');
Route::get('/profile', Profile::class)->middleware(['auth'])->name('profile.show');
Route::get('/account/change-password', ChangePassword::class)->middleware(['auth'])->name('account.change-password');
Route::post('/admin/agencies/import/preview', AgencyImportPreviewController::class)->middleware(['auth'])->name('admin.agencies.import.preview');
Route::post('/admin/agencies/{agency}/move', AgencyMoveController::class)->middleware(['auth'])->name('admin.agencies.move');
