<div class="space-y-6">
    <x-ui.page-header title="Probar API RUC" subtitle="Consulta el mismo servicio y endpoint de producción sin exponer tokens." />
    <x-ui.card title="Consulta"><form wire:submit="consult" class="grid gap-5 lg:grid-cols-3">
        <x-ui.input wire:model="ruc" label="RUC" inputmode="numeric" pattern="[0-9]{11}" minlength="11" maxlength="11" required :error="$errors->first('ruc')" />
        <div><span class="mb-2 block text-sm font-medium">Modo</span><label class="block"><input type="radio" wire:model.live="mode" value="internal"> Servicio interno</label><label class="mt-2 block"><input type="radio" wire:model.live="mode" value="endpoint"> Endpoint API</label></div>
        @if($mode === 'endpoint')<x-ui.dropdown-select id="ruc-token" wire:model="tokenId" label="Token de referencia" :value="$tokenId" :options="[0 => 'Selecciona un token'] + $tokens->mapWithKeys(fn ($token) => [$token->id => $token->name.' · '.implode(', ', $token->abilities ?? [])])->all()" :error="$errors->first('tokenId')" />@endif
        <div class="flex gap-3 lg:col-span-3"><x-ui.button type="submit" loading-target="consult">Consultar</x-ui.button><x-ui.button type="button" variant="secondary" wire:click="clear">Limpiar</x-ui.button></div>
    </form></x-ui.card>
    @if($errorMessage)<x-ui.alert tone="danger">{{ $errorMessage }}</x-ui.alert>@endif
    @if($result)<x-ui.card title="Resultado"><div class="mb-4 flex gap-3"><x-ui.badge tone="success">HTTP {{ $technical['http_status'] }}</x-ui.badge><x-ui.badge>{{ $technical['source'] === 'cache' ? 'Caché' : 'Base interna' }}</x-ui.badge><span>{{ $technical['response_time_ms'] }} ms</span></div><dl class="grid gap-4 md:grid-cols-2">@foreach(['ruc'=>'RUC','razon_social'=>'Razón social','estado'=>'Estado','condicion'=>'Condición','ubigeo'=>'Ubigeo','direccion'=>'Dirección','departamento'=>'Departamento','provincia'=>'Provincia','distrito'=>'Distrito'] as $key=>$label)<div class="rounded-[var(--radius-control)] bg-white/5 p-4"><dt class="text-xs text-[color:var(--color-text-muted)]">{{ $label }}</dt><dd class="mt-1">{{ $result[$key] ?? '—' }}</dd><x-ui.button type="button" variant="ghost" x-on:click="$dispatch('codered-copy', { value: @js($result[$key] ?? '') })">Copiar</x-ui.button></div>@endforeach</dl><x-ui.button type="button" class="mt-5" variant="secondary" x-on:click="$dispatch('codered-copy', { value: @js($copyJson) })">Copiar JSON</x-ui.button></x-ui.card>@endif
    @if($technical)<x-ui.card title="Detalles técnicos"><dl class="grid gap-3 md:grid-cols-2"><div>Origen: {{ $technical['source'] }}</div><div>Caché: {{ $technical['cached'] ? 'Sí' : 'No' }}</div><div>Token: {{ $technical['token_name'] ?? 'No aplica' }}</div><div>Ability: {{ $technical['ability_verified'] ? 'ruc:consultar' : 'No aplica' }}</div><div>Fecha: {{ $technical['tested_at'] }}</div></dl></x-ui.card>@endif
</div>
