<?php

return [
    'enabled' => (bool) env('RUC_ENABLED', true),
    'cache_enabled' => (bool) env('RUC_CACHE_ENABLED', true),
    'cache_ttl' => (int) env('RUC_CACHE_TTL', 3600),
    'rate_limit_per_minute' => (int) env('RUC_RATE_LIMIT_PER_MINUTE', 60),
    'search_rate_limit_per_minute' => (int) env('RUC_SEARCH_RATE_LIMIT_PER_MINUTE', 20),
    'search_min_length' => (int) env('RUC_SEARCH_MIN_LENGTH', 3),
    'search_max_results' => (int) env('RUC_SEARCH_MAX_RESULTS', 100),
    'stalled_after_seconds' => (int) env('RUC_IMPORT_STALLED_AFTER_SECONDS', 180),
    'import' => [
        'disk' => env('RUC_IMPORT_DISK', 'local'),
        'incoming_directory' => env('RUC_IMPORT_INCOMING_DIRECTORY', 'private/ruc/incoming'),
        'working_directory' => env('RUC_IMPORT_WORKING_DIRECTORY', 'private/ruc/working'),
        'archive_directory' => env('RUC_IMPORT_ARCHIVE_DIRECTORY', 'private/ruc/archive'),
        'errors_directory' => env('RUC_IMPORT_ERRORS_DIRECTORY', 'private/ruc/errors'),
        'queue' => env('RUC_IMPORT_QUEUE', 'ruc-imports'),
        'encoding' => env('RUC_IMPORT_ENCODING', 'ISO-8859-1'),
        'delimiter' => env('RUC_IMPORT_DELIMITER', '|'),
        'chunk_size' => (int) env('RUC_IMPORT_CHUNK_SIZE', 10000),
        'copy_batch_size' => (int) env('RUC_IMPORT_COPY_BATCH_SIZE', 100000),
        'progress_interval' => (int) env('RUC_IMPORT_PROGRESS_INTERVAL', 10000),
        'checkpoint_interval' => (int) env('RUC_IMPORT_CHECKPOINT_INTERVAL', 50000),
        'timeout' => (int) env('RUC_IMPORT_TIMEOUT', 86400),
        'lock_seconds' => (int) env('RUC_IMPORT_LOCK_SECONDS', 172800),
        'resume_enabled' => (bool) env('RUC_IMPORT_RESUME_ENABLED', true),
        'archive_files' => (bool) env('RUC_IMPORT_ARCHIVE_FILES', true),
        'strategy' => env('RUC_IMPORT_STRATEGY', 'insert_ignore'),
        'max_size_mb' => (int) env('RUC_IMPORT_MAX_SIZE_MB', 30000),
        'sync_hash_max_mb' => (int) env('RUC_IMPORT_SYNC_HASH_MAX_MB', 100),
        'retention_days' => (int) env('RUC_IMPORT_RETENTION_DAYS', 180),
        'error_retention_days' => (int) env('RUC_IMPORT_ERROR_RETENTION_DAYS', 365),
        'staging_unlogged' => (bool) env('RUC_IMPORT_STAGING_UNLOGGED', true),
        'validate_checksum' => (bool) env('RUC_IMPORT_VALIDATE_CHECKSUM', true),
    ],
];
