<div class="space-y-6">
 <x-ui.page-header eyebrow="Identidad" title="Importaciones RENIEC" subtitle="Procesamiento masivo mediante archivo privado, staging PostgreSQL y worker exclusivo."><x-slot:actions><x-ui.button wire:click="scanFiles" loading-target="scanFiles">Detectar archivos</x-ui.button></x-slot:actions></x-ui.page-header>
 <x-ui.alert tone="info" title="Archivos disponibles en el servidor">Copia el TXT a <code>storage/app/private/reniec/incoming/</code>. La plataforma no transfiere padrones RENIEC mediante HTTP o Livewire.</x-ui.alert>
 <x-ui.card title="Diagnóstico del directorio">
  <dl class="grid gap-3 text-sm md:grid-cols-2 xl:grid-cols-4"><div>Disk: <strong>{{ $diagnostics['disk'] }}</strong></div><div>Directorio: <strong>{{ $diagnostics['configured_directory'] }}</strong></div><div>Existe: <strong>{{ $diagnostics['exists'] ? 'Sí' : 'No' }}</strong></div><div>Legible: <strong>{{ $diagnostics['readable'] ? 'Sí' : 'No' }}</strong></div><div>Archivos TXT: <strong>{{ $diagnostics['txt_count'] }}</strong></div><div>Espacio libre: <strong>{{ number_format($diagnostics['free_space_bytes'] / 1073741824, 2) }} GB</strong></div><div class="md:col-span-2">Ruta física: <strong class="break-all font-mono">{{ $diagnostics['physical_path'] }}</strong></div></dl>
 </x-ui.card>
 @if($validationMessage)<x-ui.alert tone="success">{{ $validationMessage }}</x-ui.alert>@endif
 <x-ui.card title="Archivos disponibles en el servidor">
  <div class="mb-4 max-w-sm"><x-ui.dropdown-select wire:model="strategy" label="Estrategia para nuevos registros" :value="$strategy" :options="['insert_ignore'=>'Insertar nuevos e ignorar existentes','upsert'=>'Insertar y actualizar cambios']" /></div>
  <x-ui.table><thead><tr><th>Nombre</th><th>Tamaño</th><th>Modificado</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>
   @forelse($availableFiles as $file)<tr wire:key="reniec-file-{{ md5($file['path']) }}"><td>{{ $file['name'] }}</td><td>{{ number_format($file['size']/1048576,2) }} MB</td><td>{{ \Carbon\Carbon::createFromTimestamp($file['last_modified'])->format('d/m/Y H:i:s') }}</td><td><x-ui.badge>{{ str_replace('_',' ',$file['status']) }}</x-ui.badge></td><td><div class="flex flex-wrap gap-2"><x-ui.button size="sm" variant="secondary" wire:click="validateFile(@js($file['path']))">Validar</x-ui.button>@if($file['status']==='no_registrado')<x-ui.button size="sm" wire:click="registerFile(@js($file['path']))">Registrar</x-ui.button>@elseif($file['status']==='registrado' && $file['import_id'])<x-ui.button size="sm" variant="success" wire:click="startImport({{ $file['import_id'] }})">Iniciar importación</x-ui.button>@endif</div></td></tr>
   @empty<tr><td colspan="5"><x-ui.empty-state title="No hay archivos TXT" description="Copia un archivo al directorio mostrado y pulsa Detectar archivos." /></td></tr>@endforelse
  </tbody></x-ui.table>
 </x-ui.card>
 @if($active)<x-ui.card wire:poll.5s title="Importación activa" description="{{ $active->original_filename }}"><div class="grid gap-3 md:grid-cols-4 text-sm"><div>Fase: <strong>{{ $active->status->value }}</strong></div><div>Línea: <strong>{{ number_format($active->current_line_number) }}</strong></div><div>Offset: <strong>{{ number_format($active->current_byte_offset) }}</strong></div><div>Velocidad: <strong>{{ number_format($active->rows_per_second,2) }}/s</strong></div><div>Válidas: <strong>{{ number_format($active->valid_rows) }}</strong></div><div>Inválidas: <strong>{{ number_format($active->invalid_rows) }}</strong></div><div>Checkpoint: <strong>{{ $active->last_completed_chunk }}</strong></div><div>Heartbeat: <strong>{{ $active->last_heartbeat_at?->diffForHumans() ?? 'Pendiente' }}</strong></div></div><div class="mt-4 flex gap-2"><x-ui.button variant="warning" wire:click="pause({{ $active->id }})">Pausar</x-ui.button><x-ui.button variant="danger" wire:click="cancel({{ $active->id }})">Cancelar</x-ui.button></div></x-ui.card>@endif
 <x-ui.card title="Historial"><x-ui.table><thead><tr><th>Archivo</th><th>Estado</th><th>Estrategia</th><th>Procesadas</th><th>Nuevas</th><th>Actualizadas</th><th>Inválidas</th><th>Acciones</th></tr></thead><tbody>@forelse($imports as $import)<tr><td>{{ $import->original_filename }}</td><td><x-ui.badge>{{ $import->status->value }}</x-ui.badge></td><td>{{ $import->strategy }}</td><td>{{ number_format($import->processed_rows) }}</td><td>{{ number_format($import->inserted_rows) }}</td><td>{{ number_format($import->updated_rows) }}</td><td>{{ number_format($import->invalid_rows) }}</td><td>@if(in_array($import->status,[\App\Modules\Reniec\Enums\ReniecImportStatus::Paused,\App\Modules\Reniec\Enums\ReniecImportStatus::Failed],true))<x-ui.button size="sm" wire:click="resume({{ $import->id }})">Reanudar</x-ui.button>@endif</td></tr>@empty<tr><td colspan="8"><x-ui.empty-state title="No hay importaciones RENIEC" description="Copia un padrón al directorio privado para comenzar." /></td></tr>@endforelse</tbody></x-ui.table><x-ui.pagination :paginator="$imports" /></x-ui.card>
</div>
